parameters:
  - name: projectName
    type: string
    default: flint
    
  - name: pythonVersion
    type: string
    default: 3.11
    
  - name: pythonSrcDirectory
    type: string
    default: $(Build.Repository.LocalPath)/src
    
  - name: pythonTestsDirectory
    type: string
    default: $(Build.Repository.LocalPath)/tests

  - name: pythonPyprojectFilepath
    type: string
    default: $(Build.Repository.LocalPath)/src/pyproject.toml
    
resources:
  repositories:
    - repository: azuredevops
      type: github
      name: YourGithubUsername/.azuredevops
      endpoint: github
      ref: main

stages:
- stage: CodeQuality
  displayName: Code Quality
  jobs:
  - job: CodeQuality
    displayName: Code Quality
    steps:
    - checkout: self
      submodules: recursive

    - task: UsePythonVersion@0
      inputs:
        versionSpec: ${{ parameters.pythonVersion }}

    - template: v1/templates/atomic/python/poetry-install-pyproject.yaml@azuredevops
      parameters:
        targetPath: ${{ parameters.pythonSrcDirectory }}
        pythonPyprojectFilepath: ${{ parameters.pythonPyprojectFilepath }}

    - template: v1/templates/composite/python/formatter.yaml@azuredevops
      parameters:
        pythonSrcDirectory: ${{ parameters.pythonSrcDirectory }}

    - template: v1/templates/composite/python/linter.yaml@azuredevops
      parameters:
        pythonSrcDirectory: ${{ parameters.pythonSrcDirectory }}

    - template: v1/templates/composite/python/typechecking.yaml@azuredevops
      parameters:
        pythonSrcDirectory: ${{ parameters.pythonSrcDirectory }}
