parameters:
  - name: pythonVersion
    type: string
    default: 3.11
    
  - name: pythonSrcDirectory
    type: string
    default: $(Build.Repository.LocalPath)/src
    
  - name: pythonTestsDirectory
    type: string
    default: $(Build.Repository.LocalPath)/tests

  - name: pythonPyprojectFilepath
    type: string
    default: $(Build.Repository.LocalPath)/pyproject.toml
    
resources:
  repositories:
    - repository: azuredevops
      type: github
      name: KrijnvanderBurg/.azuredevops
      endpoint: KrijnvanderBurg
      ref: main

stages:
  - template: /.azuredevops/v1/pipelines/flint.yaml@azuredevops
    parameters:
      pythonVersion: ${{ parameters.pythonVersion }}
      pythonSrcDirectory: ${{ parameters.pythonSrcDirectory }}
      pythonTestsDirectory: ${{ parameters.pythonTestsDirectory }}
      pythonPyprojectFilepath: ${{ parameters.pythonPyprojectFilepath }}
