# This is a minimal implementation that only uses the flint.yaml template
parameters:
  - name: pythonVersion
    type: string
    default: 3.11
    
  - name: pythonSrcDirectory
    type: string
    default: $(Build.Repository.LocalPath)/src
    
  - name: pythonTestsDirectory
    type: string
    default: $(Build.Repository.LocalPath)/tests

  - name: pythonPyprojectFilepath
    type: string
    default: $(Build.Repository.LocalPath)/pyproject.toml
    
resources:
  repositories:
    - repository: flint
      type: github
      name: YourOrganization/flint-pipeline-templates # Replace with actual org/repo
      endpoint: GitHubConnection # Replace with your service connection name
      ref: main

stages:
  # Extend the flint pipeline template
  - template: pipelines/flint.yaml@flint
    parameters:
      # Required parameters
      pythonVersion: ${{ parameters.pythonVersion }}
      pythonSrcDirectory: ${{ parameters.pythonSrcDirectory }}
      pythonTestsDirectory: ${{ parameters.pythonTestsDirectory }}
      pythonPyprojectFilepath: ${{ parameters.pythonPyprojectFilepath }}
      
      # Optional parameters - uncomment and adjust as needed based on the flint template requirements
      # enableCodeCoverage: true
      # minCodeCoveragePercent: 80
      # enableSecurityScans: true
      # artifactName: flint-package
