resources:
  repositories:
  - repository: cicd
    type: git
    name: CompliancyCarnivalCacophony/python.wheel.cicd
    ref: refs/heads/feature/add_pylint_configs

trigger:
  branches:
    include:
    - main

extends:
  template: cicd.yml@cicd
