resources:
  repositories:
  - repository: cicd
    type: git
    name: CompliancyCarnivalCacophony/az.templates.cicd.python.wheel
    ref: refs/heads/main

trigger:
  branches:
    include:
    - main

extends:
  template: deployment/azure-pipelines.yml@cicd
  parameters:
    pythonVersion: 3.11
    coveragePath: .
    