resources:
  repositories:
  - repository: cicd
    type: git
    name: CompliancyCarnivalCacophony/az.cicd.templates
    ref: refs/heads/main

trigger:
  branches:
    include:
    - main

extends:
  template: /pipelines/python/wheel/azure-pipelines.yml@cicd
  parameters:
    pythonVersion: 3.11
    coveragePath: .
    