services:
    devcontainer:
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VARIANT: ubuntu-24.04
            target: base
        volumes:
            - ../../:/workspace:cached
            - devcontainer-bashhistory:/commandhistory
            - poetry-cache:/home/vscode/.cache/pypoetry
        command: sleep infinity
volumes:
    profile:
    devcontainer-bashhistory:
    poetry-cache:
