name: 'Ruff Linter'
description: 'Lint code using Ruff'
inputs:
  target-path:
    description: 'Path to lint'
    required: false
    default: '.'
  config-file:
    description: 'Path to ruff configuration file'
    required: false
    default: '.devcontainer/.dotfiles/python/ruff.toml'

runs:
  using: 'composite'
  steps:
    - name: Run Ruff linter
      shell: bash
      run: |
        CONFIG_ARG=""
        if [ -f "${{ inputs.config-file }}" ]; then
          CONFIG_ARG="--config ${{ inputs.config-file }}"
        fi
        
        poetry run ruff check \
          --output-format=github \
          $CONFIG_ARG \
          ${{ inputs.target-path }}
