name: 'Setup Poetry'
description: 'Install and configure Poetry without virtualenv'
inputs:
  poetry-version:
    description: 'Poetry version to install'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --user pipx
        python -m pipx ensurepath
        pipx install poetry${{ inputs.poetry-version != 'latest' && format('=={0}', inputs.poetry-version) || '' }}
    
    - name: Configure Poetry
      shell: bash
      run: |
        poetry config virtualenvs.create false
        poetry config virtualenvs.in-project false
        poetry --version
