name: Pylint
description: Run Pylint linter on Python code
inputs:
  target-path:
    description: Path to the directory to lint
    required: false
  config-file:
    description: Path to the Pylint configuration file
    required: false

runs:
  using: composite
  steps:
    - name: Run Pylint
      shell: bash
      run: |
        sh ${{ github.workspace }}/.github/scripts/run-pylint.sh \
          "${{ inputs.target-path }}" \
          "${{ inputs.config-file }}"
