name: Ruff Linter
description: Run Ruff linter on Python code
inputs:
  target-path:
    description: Path to the directory to lint (default: entire repo)
    required: false
  config-file:
    description: Path to the Ruff configuration file
    required: false

runs:
  using: composite
  steps:
    - name: Run Ruff linter
      shell: bash
      run: |
        sh ${{ github.workspace }}/scripts/ruff_linter.sh \
          "${{ inputs.target-path }}" \
          "${{ inputs.config-file }}"
