version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        PYTHON_VERSION: 3.12.1
      target: base
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
