name: 'Bandit Security Scanner'
description: 'Scan for security issues using Bandit'
inputs:
  target-path:
    description: 'Path to scan'
    required: false
    default: '.'
  config-file:
    description: 'Path to bandit configuration file'
    required: false
    default: '.devcontainer/.dotfiles/python/bandit.ini'

runs:
  using: 'composite'
  steps:
    - name: Run Bandit
      shell: bash
      run: |
        CONFIG_ARG=""
        if [ -f "${{ inputs.config-file }}" ]; then
          CONFIG_ARG="--configfile ${{ inputs.config-file }}"
        fi
        
        poetry run bandit \
          --recursive \
          --format json \
          --output bandit-report.json \
          $CONFIG_ARG \
          ${{ inputs.target-path }} || true
        
        # Also output to console
        poetry run bandit \
          --recursive \
          --format screen \
          $CONFIG_ARG \
          ${{ inputs.target-path }}
    
    - name: Upload Bandit results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-results
        path: bandit-report.json
