name: 'isort Formatter'
description: 'Run isort formatter on Python code'
inputs:
  target-path:
    description: 'Path to the directory to format (default: entire repo)'
    required: false
  config-file:
    description: 'Path to the isort configuration file'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run isort formatter
      shell: bash
      run: |
        sh ${{ github.workspace }}/scripts/isort.sh \
          "${{ inputs.target-path }}" \
          "${{ inputs.config-file }}"
