name: Poetry Setup
description: Install and configure Poetry without virtualenv

runs:
  using: composite
  steps:
    - name: Install Poetry
      shell: bash
      run: sh ${{ github.workspace }}/scripts/poetry-setup.sh
