name: Install Package
description: Install built wheel package
inputs:
  wheel-path:
    description: Path to the wheel file
    required: false

runs:
  using: composite
  steps:
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Package
      shell: bash
      run: |
        sh ${{ github.workspace }}/.github/scripts/install-package.sh \
          "${{ inputs.wheel-path }}"
