name: 'TruffleHog Secret Scanner'
description: 'Scan for secrets using TruffleHog'
inputs:
  target-path:
    description: 'Path to scan'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ${{ inputs.target-path }}
        base: main
        head: HEAD
        extra_args: --debug --only-verified
