name: Auto-format

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.11'

jobs:
  check-formatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: false

      - name: Install dependencies
        uses: ./.github/actions/atomic/poetry-install

      - name: Check code formatting
        uses: ./.github/actions/composite/python-formatters
        with:
          target-path: src
