name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatters-and-linters:
    name: Formatters & Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: ./.github/actions/setup-python
        with:
          python-version: 3.12
      
      - name: Install Poetry
        uses: ./.github/actions/setup-poetry
      
      # Formatters
      - name: Run Ruff Formatter
        uses: ./.github/actions/run-ruff-formatter
      
      # Linters
      - name: Run Ruff Linter
        uses: ./.github/actions/run-ruff-linter
      
      - name: Run Flake8
        uses: ./.github/actions/run-flake8
      
      - name: Run Pylint
        uses: ./.github/actions/run-pylint
      
      # Type Checkers
      - name: Run Mypy
        uses: ./.github/actions/run-mypy
      
      - name: Run Pyright
        uses: ./.github/actions/run-pyright
      
      # Dead Code Detector
      - name: Run Vulture (Dead Code)
        uses: ./.github/actions/run-vulture

  security:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for secret scanning
      
      - name: Install Python
        uses: ./.github/actions/setup-python
        with:
          python-version: 3.12
      
      - name: Install Poetry
        uses: ./.github/actions/setup-poetry
      
      - name: Install project dependencies
        run: poetry install --no-interaction --no-ansi
      
      - name: Run Bandit
        uses: ./.github/actions/run-bandit
      
      - name: Run Semgrep
        uses: ./.github/actions/run-semgrep
      
      - name: Run Trufflehog (Secrets)
        uses: ./.github/actions/run-trufflehog
      
      - name: Run Ossaudit
        uses: ./.github/actions/run-ossaudit
      