name: Dependency Update

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: '3.11'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Update dependencies
        run: |
          poetry update
          poetry lock --no-update

      - name: Install updated dependencies
        uses: ./.github/actions/atomic/poetry-install

      - name: Run quick tests
        uses: ./.github/actions/atomic/pytest
        with:
          tests-path: tests/unit
          coverage-path: src

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "🔄 Automated dependency update"
          body: |
            This PR updates project dependencies to their latest versions.
            
            **Changes:**
            - Updated all dependencies to latest compatible versions
            - Updated poetry.lock file
            
            **Testing:**
            - ✅ Unit tests passed
            - ✅ Dependencies installed successfully
            
            Please review the changes and ensure all tests pass before merging.
          branch: automated/dependency-update
          delete-branch: true
          labels: |
            dependencies
            automated
