name: Release Python App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: ./.github/actions/setup-python
        with:
          python-version: 3.13
      
      - name: Setup Poetry
        uses: ./.github/actions/poetry-setup
      
      - name: Get version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(sh ${{ github.workspace }}/.github/scripts/poetry-get-version.sh)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      
      # Add release steps here
      # Use ${{ steps.get_version.outputs.version }} to access the version
