name: Release Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  release:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Display version
        run: echo "Version to release is ${{ needs.build-and-test.outputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build-and-test.outputs.version }}
          name: Release v${{ needs.build-and-test.outputs.version }}
          files: dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
